service: football
frameworkVersion: "3"

provider:
  name: aws
  runtime: python3.9
  region: us-east-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ssm:GetParameter"
      Resource:
        - "*"
    - Effect: "Allow"
      Action:
        - "s3:GetObject"
        - "s3:PutObject"
        - "s3:HeadObject"
      Resource:
        - "arn:aws:s3:::${self:custom.s3Bucket}/*"
        - "arn:aws:s3:::${self:custom.s3Bucket}"


plugins:
  - serverless-hooks-plugin


custom:
  s3Bucket: zsbtest
  hooks:
    "package:initialize":
      - echo "begin build container..."
      - podman build -t 730335571595.dkr.ecr.us-east-1.amazonaws.com/zsbtestecr:football .
      - echo "begin push container..."
      - podman push 730335571595.dkr.ecr.us-east-1.amazonaws.com/zsbtestecr:football


functions:
  web:
    image: 730335571595.dkr.ecr.us-east-1.amazonaws.com/zsbtestecr:football
    timeout: 30
    memorySize: 512
    events:
      - httpApi:
          path: /get_csv
          method: get
      - httpApi:
          path: /summarize
          method: get
      - httpApi:
          path: /query_kpi_from_csv
          method: post

